name: test

on: [push]

jobs:
  build:
    name: >-
      Ruby: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{ matrix.ruby }}-${{ hashFiles(format('{0}{1}', github.workspace, '/zen_to_i.gemspec')) }}
        restore-keys: |
          bundle-use-ruby-${{ matrix.ruby }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: run rspec
      run: |
        bundle exec rspec
