name: test

on: [push]

jobs:
  build:
    name: >-
      Ruby: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.4.9'
          - '2.5.7'
          - '2.6.5'
          - '2.7.0'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/local/rubies
        key: ruby-${{ matrix.ruby }}
    - name: setup ruby
      uses: clupprich/ruby-build-action@master
      id: ruby
      with:
        ruby-version: ${{ matrix.ruby }}
        cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}
    - name: bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: run rspec
      run: |
        bundle exec rspec
